apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pushProxyServiceName }}
  labels:
    app: {{ .Values.pushProxyLabel }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.pushProxyPort }}
    targetPort: {{ .Values.pushProxyPort }}
    protocol: TCP
    name: {{ .Values.pushProxyServiceName }}
  selector:
    app: {{ .Values.pushProxyLabel }}