apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mattermostServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: {{ .Values.mattermostServiceName }}
  selector:
    app: {{ .Chart.Name }}
