apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.databaseRcName}}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    app: {{ .Values.databaseRcName }}
  template:
    metadata:
      name: {{ .Values.databaseRcName}}
      labels:
        app: {{ .Values.databaseRcName }}
    spec:
      containers:
      - name: {{ .Values.databaseRcName }}
        image: {{.Values.imageRegistryPostgres}}:{{.Values.imageTagPostgres}}
        imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy | quote }}
        env:
         - name: POSTGRES_DB
           valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef}}
              key: database-name
         - name: POSTGRES_USER
           valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef}}
              key: database-username
         - name: POSTGRES_PASSWORD
           valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef}}
              key: database-password