kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secretRef }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  database-port: {{ b64enc "5544" }}
  database-username: {{ b64enc "mmuser" }}
  database-password: {{ b64enc "mmpassword" }}
  database-name: {{ b64enc "mattermost" }}
  android-api-key: {{ b64enc "AIzaSyCnbHEzZd_WlbuFLE_GV2AQi3AnkjTYAdk" }}