#!/bin/sh

cat << EOF > /config/mattermost-push-proxy.json
{
    "ListenAddress":":8066",
    "ThrottlePerSec":300,
    "ThrottleMemoryStoreSize":50000,
    "ThrottleVaryByHeader":"X-Forwarded-For",
    "EnableMetrics": false,
    "AndroidPushSettings":[
        {
            "Type":"android",
            "AndroidApiKey":"${ANDROIDAPIKEY}"
        },
        {
            "Type":"android_rn",
            "AndroidApiKey":"${ANDROIDAPIKEY}"
        }
    ],
    "ApplePushSettings":[
        {
            "Type":"apple",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":${APPLEPUSHCERTPRIVATE},
            "ApplePushCertPassword":${APPLEPUSHCERTPASSWORD},
            "ApplePushTopic":"com.mattermost.Mattermost"
        },
        {
            "Type":"apple_rn",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":"./config/mattermost_production_priv.pem",
            "ApplePushCertPassword":${APPLEPUSHCERTPASSWORD},
            "ApplePushTopic":"com.mattermost.react.native"
        }
    ]
}
EOF
