namespace: "default"
mattermostServerName: "mattermost-server"
imageTagMattermost: "3"
imagePullPolicy: "Always"
databaseRcName: "postgres-mattermost"
imageRegistryPostgres: "postgres"
imageTagPostgres: "9"
postgresDb: "mattermost"
databaseHost: "postgreshost"
secretRef: "mattermost.secret"
databaseServiceName: "postgres"
databaseTargetPort: "5432"
mattermostServiceName: "mattermost"
pushNotificationContents: "generic"
pushProxyServiceName: "mattermost-push-proxy"
pushProxyLabel: "mm-push-proxy"
pushProxyPort: "8066"
pushProxyRcName: "mattermost-push-proxy"
imageRegistryPushProxy: "syedahmedmohiuddinpeerzade"
imageRegistryServer: "syedahmedmohiuddinpeerzade"
imageRepoServer: "mattermost-server"
imageRepoPushProxy: "mattermost-push-proxy"
imageTagPushProxy: "latest"
imageTagServer: "latest"
androidApiKeyName: "ANDROIDAPIKEY"
applePushCertificateName: "APPLEPUSHCERTPRIVATE"
applePushCertPassword: "APPLEPUSHCERTPASSWORD"
